[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (client build output)
  publish = "dist/client"
  
  # Functions directory for serverless API
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Enable TypeScript support
  NPM_FLAGS = "--production=false"

# Redirect all API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - redirect all non-API routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "editor", "user"]}

# Catch-all for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.neon.tech https://*.neon.tech"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Edge functions (if needed for advanced routing)
[edge_functions]
  # Can be configured later for advanced use cases